export enum ErrorCode {
  UNKNOWN_ERR = 0,
  DATABASE_CONSTRAINT_ERR = 1,
  NETWORK_ERR = 2,
  ILLEGAL_STATE_ERR = 3,
  NOT_ENOUGH_VALUE_ERR = 4,
  ESSENTIAL_DATA_MISSED = 5,
  NOT_FOUND_CURRENT_CHAIN_NETWORK = 6,
}
